[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "synnax-shared"
version = "0.0.0"
description = "Synnax shared Python pacakges"
readme = "README.md"
requires-python = ">=3.10"

dependencies = []

[project.optional-dependencies]
system-token-issuer = ["boto3", "boto3-stubs[lambda]", "PyJWT"]
http-bearer-token-client = ["requests", "types-requests"]
dev = ["mypy", "black"]
all = ["synnax-shared[system-token-issuer,http-bearer-token-client,dev]"]

[tool.hatch.build.targets.sdist]
include = ["/src"]
